export const mozjpegOptions = {
	quality: 75,
	progressive: true,
	targa: false,
	revert: false,
	fastCrush: false,
	dcScanOpt: 2,
	trellis: true,
	trellisDC: true,
	tune: 'hvs-psnr',
	overshoot: true,
	arithmetic: true,
	dct: 'int',
	quantBaseline: false,
	quantTable: 3,
	smooth: 3,
	maxMemory: 2,
	sample: 'HxV',
};
