export const svgOptions = [{
	name: 'removeViewBox',
	active: false,
	removeDoctype: true,
	removeXMLProcInst: true,
	removeComments: true,
	removeMetadata: true,
	removeXMLNS: true,
	removeEditorsNSData: true,
	cleanupAttrs: true,
	inlineStyles: true,
	minifyStyles: true,
	convertStyleToAttrs: true,
	cleanupIDs: true,
	//prefixIds,
	removeRasterImages: false,
	removeUselessDefs: true,
	cleanupNumericValues: true,
	cleanupListOfValues: false,
	convertColors: true,
	removeUnknownsAndDefaults: true,
	removeNonInheritableGroupAttrs: true,
	removeUselessStrokeAndFill: true,
	removeViewBox: false,
	cleanupEnableBackground: true,
	removeHiddenElems: true,
	removeEmptyText: true,
	convertShapeToPath: true,
	moveElemsAttrsToGroup: true,
	moveGroupAttrsToElems: true,
	collapseGroups: true,
	convertPathData: true,
	convertTransform: true,
	convertEllipseToCircle: true,
	removeEmptyAttrs: true,
	removeEmptyContainers: true,
	mergePaths: true,
	removeUnusedNS: false,
	// This currently throws an error
	//removeOffCanvasPaths,
	reusePaths: false,
	sortAttrs: true,
	sortDefsChildren: true,
	removeTitle: true,
	removeDesc: true,
	removeDimensions: false,
	//removeAttrs,
	//removeElementsByAttr,
	//removeAttributesBySelector,
	//addClassesToSVGElement,
	removeStyleElement: false,
	removeScriptElement: false
	//addAttributesToSVGElement,
}];
